#!/usr/bin/env ruby

ENV['RACK_ENV'] ||= 'development'

# Using the boot script
require File.join(File.expand_path('.'), 'config', 'boot')

# prevent STDOUT & STDERR to be reopened (apps do this to be able to log under Passenger)
def STDOUT.reopen(*args); end
def STDERR.reopen(*args); end

begin
  require "pry"
  Interpreter = Pry
rescue LoadError
  require "irb"
  require "irb/completion"
  Interpreter = IRB
end

# START
Interpreter.start